"""Followers

Revision ID: c6142b0e38d2
Revises: e6510b565c13
Create Date: 2019-05-09 21:18:28.779655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6142b0e38d2'
down_revision = 'e6510b565c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('followers',
    sa.Column('follower_email', sa.String(length=140), nullable=True),
    sa.Column('followed_email', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['followed_email'], ['tb_user.user_email'], ),
    sa.ForeignKeyConstraint(['follower_email'], ['tb_user.user_email'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')

    # ### end Alembic commands ###
