"""New fields: about_me, last_seen

Revision ID: e6510b565c13
Revises: ee81250fad00
Create Date: 2019-04-18 14:45:59.359994

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e6510b565c13'
down_revision = 'ee81250fad00'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tb_user',
        sa.Column('about_me', sa.String(length=140), nullable=True)
    )
    op.add_column(
        'tb_user',
        sa.Column('last_seen', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'about_me')
    op.drop_column('tb_user', 'last_seen')
    # ### end Alembic commands ###
