"""First try

Revision ID: ee81250fad00
Revises: 
Create Date: 2019-04-13 16:40:19.666557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, Sequence


# revision identifiers, used by Alembic.
revision = 'ee81250fad00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('user_seq_id')))
    op.create_table('tb_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    # ### end Alembic commands ###
